### ISSUE TITLE
Cannot add task 'wrapper' as a task with that name already exists

### ISSUE THREAD

**Issue by bra-fsn** [sheehan/job-dsl-gradle-example#104]
I would like to run this project from https://hub.docker.com/_/gradle docker image, but fails with:
```Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/home/gradle/project/build.gradle' line: 94

* What went wrong:
A problem occurred evaluating root project 'project'.
> Cannot add task 'wrapper' as a task with that name already exists.
```
If I remove the `task wrapper(type: Wrapper)` block, everything works fine.

**Comment by matthew-b-payne** [comment]
Check --> https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel4.8:configure_internal_tasks

in gradle version greater than 5 --> 
instead of ```
task wrapper(type: Wrapper) {
    ...
}
```
just do 
```
 wrapper {
    ...
}
```

**Comment by sheehan** [comment]
Thanks. I've removed the block from the example as it's not really needed.
