### ISSUE TITLE
ERROR: Type of item "example1" does not match existing type, item type can not be changed

### ISSUE THREAD

**Issue by Juanfree** [sheehan/job-dsl-gradle-example#105]
Hi,

I configured as you mentioned, but when a I run the script, always have this message:

ERROR: Type of item "example1" does not match existing type, item type can not be changed

Someone knows how configure?

Thanks in advance.

**Comment by Juanfree** [comment]
fixed

**Comment by akostadinov** [comment]
For the record, this happens when such job or folder name already exists.
