### ISSUE TITLE
Gradle sync failed: Cannot add task 'wrapper' as a task with that name already exists.

### ISSUE THREAD

**Issue by hathemi** [sheehan/job-dsl-gradle-example#106]
Here's where pointing the problem in gradle.build 
```
task wrapper(type: Wrapper) {
    gradleVersion = '2.14.1'
}
```
in gradle-wrapper.properties
` distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip
`
```
  dependencies {
        classpath 'com.android.tools.build:gradle:3.4.2'
    }
```
i have tried to change it this way 
 ```
wrapper{
    gradleVersion = '2.14.1'
}
```
but it doesn't work !!!!!
please help ??

**Comment by sheehan** [comment]
I think you can just remove that. I've removed it from the example as it's not needed.
