### ISSUE TITLE
Consider adding a license?

### ISSUE THREAD

**Issue by jbyler** [sheehan/job-dsl-gradle-example#19]
Hi Matt, thanks for publishing this example and for the related talk!  Somewhere I believe I saw a suggestion that this repository could be used as a template for others to start from.  If this is your intention, would you consider adding a license which permits this usage?  According to http://choosealicense.com/no-license/ , you automatically retain copyright over the code if you don't specify a license, meaning it can't be copied.

The same site http://choosealicense.com/ makes it easy to choose a license and explains how to add it.  And I am happy to submit a pull request with a license if you know which one you want to use.

**Comment by sheehan** [comment]
Good info. License added, thanks!

**Comment by jbyler** [comment]
Perfect, thanks!
