### ISSUE TITLE
How to include resources for tests from other plugins

### ISSUE THREAD

**Issue by Russell-IO** [sheehan/job-dsl-gradle-example#31]
Hi, I'm trying to add a plugin with an Ansible Job, would you be able to help me / point me in the right direction ?  If you can do one example as a commit .. I'd be happy to extend it with more plugins etc

Here is the jobdsl extension and the resources, just not clear where / how to extend the groovy specs to include these:

https://github.com/jenkinsci/ansible-plugin/blob/master/src/main/java/org/jenkinsci/plugins/ansible/jobdsl/AnsibleJobDslExtension.java
https://github.com/jenkinsci/ansible-plugin/tree/master/src/test/resources/jobdsl

**Comment by sheehan** [comment]
fixed by https://github.com/sheehan/job-dsl-gradle-example/pull/32
