### ISSUE TITLE
gradlew debugXml fails for example8Jobs.groovy (II)

### ISSUE THREAD

**Issue by astolz67** [sheehan/job-dsl-gradle-example#36]
Hi Matt,
Thanks a lot for looking into it.
Sorry to bother, but since 1.43 it's githubPullRequest, prior to 1.43 pullRequest.
Thus, the following warning is thrown:
Warning: (script, line 19) pullRequest is deprecated.
Any idea?
Thanks and best regards,
Andreas
P.S. was not able to re-open https://github.com/sheehan/job-dsl-gradle-example/issues/35.

**Comment by sheehan** [comment]
Sorry, I was a bit hasty. I've restored the correct (newer) syntax. 

Since that method comes from a separate plugin, it's not available when running debugXml. I've updated XmlOutputRunner to ignore the call and log a warning for now. Not ideal, but it should proceed without error at least.
