### ISSUE TITLE
Example showing how to add plugins to test jenkins instance

### ISSUE THREAD

**Issue by rocktavious** [sheehan/job-dsl-gradle-example#41]
Hello, love this project and i look forward to using it heavily at my work.  We have a lot of different plugins installed in our jenkins instance and our job dsl's utilize these plugins.  When i run the `gradle test` command i get output like this:

    Processing provided DSL script
    Warning: (script, line 11) plugin 'ansicolor' needs to be installed
    Warning: (script, line 12) plugin 'timestamper' needs to be installed
    Processing provided DSL script
    Warning: (script, line 8) version 1.12 or later of plugin 'workflow-multibranch' needs to be installed
    Warning: (script, line 22) version 5.1 or later of plugin 'cloudbees-folder' needs to be installed

I tried modifiying the `build.gradle` file in the `dependencies` section with lines like

    // plugins to install in test instance
    testPlugins 'org.jenkins-ci.plugins:workflow-cps:2.5'

But that only nets me output like so during the `gradle clean test` command

    Could not resolve all dependencies for configuration ':testPlugins'.
    > Could not find org.jenkins-ci.plugins:workflow-cps:2.5.
      Searched in the following locations:
          https://repo1.maven.org/maven2/org/jenkins-ci/plugins/workflow-cps/2.5/workflow-cps-2.5.pom
          https://repo1.maven.org/maven2/org/jenkins-ci/plugins/workflow-cps/2.5/workflow-cps-2.5.jar
          https://jcenter.bintray.com/org/jenkins-ci/plugins/workflow-cps/2.5/workflow-cps-2.5.pom
          https://jcenter.bintray.com/org/jenkins-ci/plugins/workflow-cps/2.5/workflow-cps-2.5.jar
          http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/workflow-cps/2.5/workflow-cps-2.5.pom
          http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/workflow-cps/2.5/workflow-cps-2.5.jar
      Required by:
          :data:unspecified

How does one install extra plugins to the test harness to make warnings about missing plugins that the DSL scripts use?

**Comment by rocktavious** [comment]
After some more playing around with it some more, it seems like other plugins work

    testPlugins 'org.jenkins-ci.plugins:timestamper:1.8.2'
    testPlugins 'org.jenkins-ci.plugins:ansicolor:0.4.2'

So its unclear to me why specifically `workflow-cps` is failing in this case

**Comment by rocktavious** [comment]
Also not sure if you'd like me to submit a pullrequest for this, but i ended up modifying the build.gradle file locally to support having a list of plugins

gradle.properties

    jobDslVersion=1.47
    jenkinsVersion=1.642.4
    jenkinsPlugins=["timestamper:1.8.2", "ansicolor:0.4.2"]

modifications to build.gradle

    import groovy.json.JsonSlurper
    ....
    dependencies {
        ...
        // plugins to install in test instance
        for (plugin in new JsonSlurper().parseText(jenkinsPlugins)) {
            testPlugins 'org.jenkins-ci.plugins:' + plugin
        }

This way people can easily specify extra plugins to install

Sorry If this solution is naive, I'm new to gradle.

**Comment by sheehan** [comment]
I think this behavior is new since https://github.com/sheehan/job-dsl-gradle-example/pull/39.
@daspilker, do you have a recommendation on how to handle these warnings?

**Comment by daspilker** [comment]
The Workflow CPS plugin has a different group ID: https://github.com/jenkinsci/workflow-cps-plugin/blob/workflow-cps-2.5/pom.xml#L34

So it needs to be included like this:

    testPlugins 'org.jenkins-ci.plugins.workflow:workflow-cps:2.5'

**Comment by sheehan** [comment]
Thanks @daspilker. So @rocktavious it looks like you just need to check the group ID.
