### ISSUE TITLE
How do you pass in command line arguments to a gradle dsl job?

### ISSUE THREAD

**Issue by marsinvasion** [sheehan/job-dsl-gradle-example#51]
I have a job where I can pass in command line arguments like

`gradle -Pconf=prod build`

How do I pass arguments in jobs dsl?

I tried the following but it doesn't work

```
job("doSomething"){
    steps {
       gradle('-Pconf=prod build')
    }
}
```

or

```
job("doSomething"){
    steps {
       gradle('build', '-Pconf=prod')
    }
}
```

**Comment by sheehan** [comment]
The second one should work according to [the doc](http://jenkinsci.github.io/job-dsl-plugin/#method/javaposse.jobdsl.dsl.helpers.step.StepContext.gradle). If not, I would ask on the [the mailing list](https://groups.google.com/d/forum/job-dsl-plugin) or file a [JIRA](https://issues.jenkins-ci.org/browse/JENKINS/component/16720/).
