### ISSUE TITLE
How to pass cumble header to rest api call ? CSRF 

### ISSUE THREAD

**Issue by wilau2** [sheehan/job-dsl-gradle-example#58]
Jenkins 2.0 comes with CSRF enabled by default.

According to [this](https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API#RemoteaccessAPI-CSRFProtection) it should be enable and we should pass crumble in our request header. Is it possible to pass an header with ./gradle rest ?

**Comment by sheehan** [comment]
Support for this was added [here](https://github.com/sheehan/job-dsl-gradle-example/pull/49). It should add the header for you.

**Comment by wilau2** [comment]
@sheehan Thanks a lot, I'll give it a try.
