### ISSUE TITLE
Errorr processing example4Jobs.groovy No signature of method

### ISSUE THREAD

**Issue by deshantm** [sheehan/job-dsl-gradle-example#59]
Hi I just checked out the code fresh and the seed job is throwing the following error for example4:

Processing DSL script example4Jobs.groovy
ERROR: (example4Jobs.groovy, line 27) No signature of method: javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.extendedEmail() is applicable for argument types: (example4Jobs$_run_closure2_closure3_closure7_closure8) values: [example4Jobs$_run_closure2_closure3_closure7_closure8@6f56441b]
Possible solutions: extendedEmail(), extendedEmail(java.lang.String), extendedEmail(java.lang.String, groovy.lang.Closure), extendedEmail(java.lang.String, java.lang.String), extendedEmail(java.lang.String, java.lang.String, groovy.lang.Closure), extendedEmail(java.lang.String, java.lang.String, java.lang.String)

Thanks,
Todd

**Comment by sheehan** [comment]
I think that requires the `email-ext` plugin to be installed. I'll create a list of which plugins are need to run the example files and add it to the readme.

**Comment by deshantm** [comment]
I do have the email-ext plugin in Jenkins. This particular instance of Jenkins is running ver. 1.609.1 Email Extension Plugin version 2.52

**Comment by sheehan** [comment]
Yeah on second thought `email-ext` doesn't need to be installed to create the job. What version of the job-dsl plugin do you have installed?

**Comment by deshantm** [comment]
I was running 1.40. I upgraded to 1.45 and then installed/upgraded a number of required plugins (thanks to warnings in the console output). That worked for examples through example7 and now I got a new error:

ERROR: (example8Jobs.groovy, line 19) No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.githubPullRequest() is applicable for argument types: (example8Jobs$_run_closure2_closure4_closure8) values: [example8Jobs$_run_closure2_closure4_closure8@58ddd3d2]

**Comment by sheehan** [comment]
That one actually does require the GitHub pull request builder plugin to be installed. Examples 8 and 9 both rely on support provided by other plugins.

**Comment by deshantm** [comment]
I got the GitHub pull request builder plugin and that fixed that one.

I've updated the cvs plugin to 2.12, and updated and installed a few plugins related to SCM, but I'm still getting the following:

ERROR: (example9Jobs.groovy, line 10) No signature of method: javaposse.jobdsl.dsl.helpers.ScmContext.cvsscm() is applicable for argument types: (example9Jobs$_run_closure2_closure3_closure6) values: [example9Jobs$_run_closure2_closure3_closure6@42bbeba1]

**Comment by sheehan** [comment]
Strange. I just tested it and it works for me with CVS 2.12.

**Comment by punnie** [comment]
Was there a resolution to this? I'm getting similar errors for auto-generated methods:

```
Caused by: javaposse.jobdsl.dsl.DslScriptException: (script, line 216) No signature of method: javaposse.jobdsl.dsl.helpers.triggers.TriggerContext.ghprbTrigger() is applicable for argument types: (script$_run_closure3$_closure8$_closure36$_closure45) values: [script$_run_closure3$_closure8$_closure36$_closure45@4c4c88c2]
```

Happens with `slackNotifier` as well.

Jenkins 2.33
Github Pull Request Builder 1.33.1
Slack Notifier 2.1

**Comment by deshantm** [comment]
Got it working on a new version of Jenkins!

**Comment by jeffnelson** [comment]
I also have this issue with `slackNotifier`

**Comment by summitsingh** [comment]
Could someone please help me on the similar error?
 https://stackoverflow.com/questions/46963722/jenkins-dsl-script-lightweight-checkout-not-working

So, here is my pipelineJob() Jenkins DSL Script that I am using to create Jobs in Jenkins, but when I use lightweight() in cpsScmFlowDefinition, this script doesn't work and gives me an error which I have pasted below.

I am using latest Jenkins with latest DSL Plugin. Please help me to fix this issue. Thanks.
```
pipelineJob('') {
  label('')
  definition {
    cpsScmFlowDefinition {
      scm {
        git {
          remote {
            url('')
            credentials('')
          }
          branch('')
          extensions {
            cleanBeforeCheckout()
            localBranch()
          }
        }
      }
      scriptPath('')
      lightweight(true) // error while using this
    }
  }
}
```
ERROR:
```
Processing provided DSL script
ERROR: (script, line 14) No signature of method: javaposse.jobdsl.plugin.structs.DescribableListContext.git() is applicable for argument types: (script$_run_closure1$_closure4$_closure7$_closure8$_closure9) values: [script$_run_closure1$_closure4$_closure7$_closure8$_closure9@516b358d]
Possible solutions: wait(), wait(long), with(groovy.lang.Closure), is(java.lang.Object), grep(), find()
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Collecting metadata...
Metadata collection done.
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```
