### ISSUE TITLE
"No such project" When using downstreamParameterized

### ISSUE THREAD

**Issue by timsmith00** [sheehan/job-dsl-gradle-example#86]
I am trying to build two jobs one dependent on the other, both generated using the DSL plugin.  When building the job as follows, it doesnt seem to recognize its downstream dependency(ies) on the Overview page and when I Configure the job I receive a "No such project" error on the downstream parameterized trigger step, screenshot attached.  What's odds is that the error message refers to the downstream job that I actually want.  

What am i doing wrong?  I created two separate groovy files, one for each job.  I even played with the order the jobs were built.  Lastly I compared the raw config.xml files of the original DSL generated job and one where I manually fixed the downstream trigger and it seems like the plugin version was the only material difference - some things were in slightly different places, but nothing material that I could identify.
 
![screen shot 2017-11-08 at 2 25 11 pm](https://user-images.githubusercontent.com/3811002/32572859-a193c4a8-c491-11e7-92a1-5b8176bed5bf.png)

```
job("foobar-maven-freestyle") {
  scm {
    git {
      remote { 
        url("git@github.com:acme/morefoo.git")
        credentials('abc123')
      }
      extensions {
        relativeTargetDirectory('lambda')
        }
      branch('*/master')
    }
  }
  steps {
    maven {
      rootPOM('lambda/lambda-common/pom.xml')
      goals('clean install')
    }
  }
  publishers {
    downstreamParameterized {
     trigger('foobar-lambda-common_2.10') {
        condition('SUCCESS')
        parameters {
            currentBuild()
        }
      }
    }
  }
}
```

**Comment by sheehan** [comment]
Does the downstream job have a typo in its name? 

`foobar-lamba-common_2.10`
vs
`foobar-lambda-common_2.10`

**Comment by timsmith00** [comment]
Well yes I am an idiot.
