### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Russell-IO** [sheehan/job-dsl-gradle-example#87]
russell@Russells-iMac:~/Projects/personal/job-dsl-gradle-example|master
⇒  ./gradlew clean build
:clean UP-TO-DATE
:compileJava NO-SOURCE
:compileGroovy
:processResources
:classes
:jar
:assemble
:resolveTestPlugins
:compileTestJava NO-SOURCE
:compileTestGroovy
Download https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.2/ant-1.9.2.pom
Download https://repo1.maven.org/maven2/org/apache/ant/ant-parent/1.9.2/ant-parent-1.9.2.pom
Download https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.9.2/ant-launcher-1.9.2.pom
Download https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.2/ant-1.9.2.jar
Download https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.9.2/ant-launcher-1.9.2.jar
:compileTestGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':testCompileClasspath'.
> Could not find bootstrap-core-assets.jar (org.jenkins-ci.ui:bootstrap:1.3.2).
  Searched in the following locations:
      https://jcenter.bintray.com/org/jenkins-ci/ui/bootstrap/1.3.2/bootstrap-1.3.2-core-assets.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.682 secs

**Comment by sheehan** [comment]
Thanks. I upgraded the gradle version recently. Reverting back to v2.9 resolved this issue. I'll have to look into it further.

**Comment by asRIA** [comment]
Just tested current master, and it looks that downgrading gradle to 2.9 didn't help

**Comment by lumbrel** [comment]
It seems bootstrap-core-assets.jar is not available on JCenter. Changing the order of the repositories fixes this issue. The fix is using repo.jenkins-ci.org/releases before jcenter.

However, there is another issue. This time it complains about org-netbeans-insane.jar, which exists on the jenkins-ci repo, but only the sources package. To fix this, I had to add the bits.netbeans.org/maven2 repo before the repo.jenkins-ci.org/releases repo.

I am not sure if this should be the final solution, but it has worked OK for me.

**Comment by Juanfree** [comment]
Hi @lumbrel,

Could you send the correct order for repositories configuration?
 
I have the same problem like you, when I use gradlew build, receive this message -->

Could not find bootstrap-core-assets.jar

Many Thanks!

**Comment by lumbrel** [comment]
@Juanfree This is what worked for me:

```
maven { url 'http://bits.netbeans.org/maven2' }
maven { url 'http://repo.jenkins-ci.org/releases/' }
jcenter()
mavenCentral()
````

**Comment by Juanfree** [comment]
@lumbrel when you are using something like this:

./gradlew rest -Dpattern="seed" -DbaseUrl="http://localhost:8080" -Dusername="xxx" -Dpassword="xxxx"

With the correct credentials, for you it works?

**Comment by sheehan** [comment]
It works for me with the current master.

(I deleted my cached dependency first)
```bash
➜  rm -rf ~/.gradle/caches/modules-2/files-2.1/org.jenkins-ci.ui/bootstrap/1.3.2/
```

```bash
➜  ./gradlew test
:compileJava UP-TO-DATE
:compileGroovy
:processResources
:classes
:resolveTestPlugins
:compileTestJava UP-TO-DATE
:compileTestGroovy
Download http://repo.jenkins-ci.org/releases/org/jenkins-ci/ui/bootstrap/1.3.2/bootstrap-1.3.2-core-assets.jar
:processTestResources UP-TO-DATE
:testClasses
:test

BUILD SUCCESSFUL

Total time: 35.104 secs
```

**Comment by Juanfree** [comment]
Currently it works! thanks ;)

2017-11-20 16:51 GMT+01:00 Matt Sheehan <notifications@github.com>:

**Comment by lumbrel** [comment]
This is not an issue for me, as on my project I have reordered the repositories. So only for your information, cleaning the gradle caches does not make it work in my case. It is still complaining about bootstrap package. Thanks for the awesome project!

**Comment by Russell-IO** [comment]
@sheehan it seems to be related to the Jenkins Version,
for example it works just fine 1.642, but if I use a later build i.e. 2.XX it doesn't compile

**Comment by kyounger** [comment]
Yep, I'm having issues current master, but the maven repo list @lumbrel provided resolved things.

**Comment by asRIA** [comment]
Since the solution from @lumbrel  didn't work for me I had to be more brutal: 
```groovy
    testCompile ("org.jenkins-ci.main:jenkins-war:${jenkinsVersion}") {
        // Fixes: > Could not find bootstrap-core-assets.jar (org.jenkins-ci.ui:bootstrap:1.3.2).
        exclude group: 'org.jenkins-ci.ui', module: 'bootstrap'
    }
```

**Comment by anoxape** [comment]
This hack should help:
```
repositories {
    def jenkinsRepo = 'http://repo.jenkins-ci.org/releases/'

    jcenter { artifactUrls jenkinsRepo }
    maven { url jenkinsRepo }
}
```
