### ISSUE TITLE
use DSL extensions provided by other plugins

### ISSUE THREAD

**Issue by markgargan** [sheehan/job-dsl-gradle-example#89]
Hi Matt, 
 
This is great sample springboard for job-dsl you've provided here. Wished I'd come across it sooner to be honest but sometimes you only know what you're looking for after the fact :) Here example 8 I delved into the grails-example repo but couldn't see any DSL definitions? Is this possible? I'm writing a couple of tailored jobs for our instances and was hoping to share them with the ease of say the global pipeline libraries but it doesn't seem quite so straight forward? Does this example allow you to reference DSL definitions in one repo from another? we've multiple teams with diff Jenkins instances and different seed jobs. 

Thanks,
Mark.

**Comment by sheehan** [comment]
Thanks @markgargan! I use the "Additional classpath" to pull in other libraries. I'm not sure about pipeline libraries.
