### ISSUE TITLE
ace-editor-1.0.1.jar not found

### ISSUE THREAD

**Issue by tomasnorre** [sheehan/job-dsl-gradle-example#95]
Hi,

I was facing to "performance" issue with my own JobDSL test jobs, so I wanted to test out yours. 

The problem is that the job is not running through due to ace-editor-1.0.1.jar

I've tried to browse to find another location for the plugin, but with no success. 

Any hints here? 

```
~/temp/job-dsl-gradle-example$ ./gradlew clean test
:clean
:compileJava UP-TO-DATE
:compileGroovy
:processResources
:classes
:resolveTestPlugins

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':testPlugins'.
> Could not find ace-editor.jar (org.jenkins-ci.ui:ace-editor:1.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/org/jenkins-ci/ui/ace-editor/1.0.1/ace-editor-1.0.1.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 6.837 secs
```

**Comment by sheehan** [comment]
Hi @tomasnorre. Try this workaround: https://github.com/sheehan/job-dsl-gradle-example/issues/90#issuecomment-356324425. Let me know if that doesn't work.

**Comment by tomasnorre** [comment]
Hi @sheehan 

Just cloned master, and that worked out, so expect the work around works :)
