### ISSUE TITLE
Impossible to run twice/for different users

### ISSUE THREAD

**Issue by jansenm** [sheehan/job-dsl-gradle-example#97]
Because they all try to create /tmp/jenkinsTest.tmp/ directory. And its not removed afterwards too.

Couldn't find where it comes from or how to change it. So i can't have both a jenkins and intellij running on my localhost executing this. Different users naturally.

The directory should at least contain the username. Even better some timestamp and/or random stuff.

**Comment by sheehan** [comment]
This is part of the jenkins-test-harness and should be addressed there.
https://github.com/jenkinsci/jenkins-test-harness/blob/master/src/main/java/org/jvnet/hudson/test/TemporaryDirectoryAllocator.java
